// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ME_API.Models
{
    public class MES_Audit_Org
    {
        [Key]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        [Key]
        [StringLength(1)]
        public string PDC_ID { get; set; }
        [StringLength(100)]
        public string PDC_Name { get; set; }
        [Key]
        [StringLength(3)]
        public string Line_ID { get; set; }
        [StringLength(100)]
        public string Line_Name { get; set; }
        [Key]
        [StringLength(4)]
        public string Dept_ID { get; set; }
        [StringLength(100)]
        public string Dept_Name { get; set; }
        [StringLength(100)]
        public string Building { get; set; }
        [StringLength(100)]
        public string Building_Name { get; set; }
        public int Line_Seq { get; set; }
        public int? Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
        [StringLength(16)]
        public string Updated_By { get; set; }
        [Required]
        [StringLength(100)]
        public string HP_Dept_ID { get; set; }
        public int? IsAGV { get; set; }
        [StringLength(1)]
        public string Block { get; set; }
        [Required]
        [StringLength(3)]
        public string Line_ID_2 { get; set; }
        [StringLength(100)]
        public string Line_ID_2_Name { get; set; }

        [StringLength(100)]
        public string Icon_Path { get; set;}
        [Key]
        [StringLength(1)]
        public bool? IsWT {get;set;}
        [Key]
        [StringLength(1)]
        public bool? IsSME {get;set;}
        [Key]
        [StringLength(1)]
        public bool? Is6S {get;set;}
        [Key]
        [StringLength(1)]
        public bool? IsWS {get;set;}
    }
}